Description = "Allows us to prove that solutions to certain PDE's can be expressed as infinite series"
Pre_Requisites = ["Partial Differential Equations",]
Organization = "B"
Authors = ["Ginger Gengar",]

