#!/bin/bash

cd ..

find . -type f -name '*.aux' -delete
find . -type f -name '*.log' -delete
find . -type f -name '*.out' -delete
find . -type f -name '*.sta' -delete
find . -type f -name '*.toc' -delete
find . -type f -name '*.dvi' -delete
find . -type f -name '*.fdb_latexmk' -delete
find . -type f -name '*.fls' -delete
find . -type f -name '*.sta' -delete
find . -type f -name '*.synxtex.gz' -delete

